name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build 
        env:
          VITE_ADMIN_LOGIN_URL: ${{ secrets.VITE_ADMIN_LOGIN_URL }}
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
      
      - name: Transfer files
        run: |
            cp .htaccess dist/
            cp sitemap.xml dist/
            cp robots.txt dist/

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Built test file: ({sha}) {msg}"
